name: Unit Tests

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - fastvec/**
      - tests/**
      - .github/workflows/tests.yml

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - fastvec/**
      - tests/**
      - .github/workflows/tests.yml
jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin uv
          maturin develop --release --out dist --find-interpreter
          uv sync
      - name: Run tests
        run: |
          pytest tests/

  test_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: test Rust code
        run: |
          cargo test --release
